services:
  api-rest:
    build: .
    container_name: rctv_api
    restart: always
    ports:
      - "3002:3002"
    environment:
      POST: 3002
      DB_HOST: db            # nombre del servicio de Postgres
      DB_PORT: 5432          # puerto interno de Postgres
      DB_USER: rctv
      DB_PASSWORD: rctv@01
      DB_NAME: media_db
      JWT_EXPIRES_IN: 7d
      JWT_SECRET: esamima
    volumes:
      - ./api/media:/app/media
    networks:
      - rc_media_net        # la misma red que tu contenedor DB

networks:
  rc_media_net:
    external: true
